helm:
  parameters:
  - name: frontend.image
    value: ghostwritten/frontend
    forcestring: true
  - name: frontend.tag
    value: main-5f218e9
    forcestring: true
  - name: backend.image
    value: ghostwritten/backend
    forcestring: true
  - name: backend.tag
    value: main-5f218e9
    forcestring: true
